version: "3.9"
services:
  cfsm-mysql:
    container_name: cfsm-mysql
    image: mysql:8.0.33-debian
    cap_add:
      - SYS_NICE
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=6G --group-concat-max-len=4294967295 --innodb_log_buffer_size=256M --innodb_write_io_threads=8 --innodb_flush_log_at_trx_commit=0 --innodb_doublewrite=0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cfshopmanagement
    ports:
      - 39063:3306
  cfsm-be:
    image: golang:1.20.7-bookworm
    container_name: cfsm-be
    volumes:
      - ./backend:/data
      - ./backend/tools/x86/gin:/usr/bin/gin
    working_dir: /data
    environment:
      - GOMEMLIMIT=5120MiB
    entrypoint: "/bin/bash\n -c /data/go-server.sh"
    ports:
      - 8080:8080
    depends_on:
      - cfsm-mysql
    links:
      - cfsm-mysql
