version: "3.9"
services:
  cfsm-mysql:
    container_name: cfsm-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cfshopmanagement
    ports:
      - 39063:3306
  cfsm-be:
    image: golang:1.20.7-bookworm
    container_name: cfsm-be
    volumes:
      - ./backend:/data
    working_dir: /data
    environment:
      - GOMEMLIMIT=5120MiB
    entrypoint: "/bin/bash\n -c /data/go-server.sh"
    ports:
      - 8080:8080
    depends_on:
      - cfsm-mysql
    links:
      - cfsm-mysql
